### ISSUE TITLE
[Bug]: Epic Fight crash

### ISSUE THREAD

**Issue by loopel** [dr3ams/Roguelike-Adventures-and-Dungeons-2#365]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.8

### Describe your issue

So I was exploring a dungeon underground, (the crash happens only underground) and it will crash a few minutes into loading into my world with mobs underground.

### Steps to reproduce the issue

Go to a singleplayer world. Go underground. Encounter some kind of mob, as it is not always the same mob, visible or not, crash

### Additional Information

https://pastebin.com/bp8i4ESF <-crash report
https://gist.github.com/loopel/a4c450da04ad66a63a2e74463d4ead49 <-latest.log
