### ISSUE TITLE
[Bug]: Server Crash when trying to paint Inventory Hopper - 1.10a [Tracker]

### ISSUE THREAD

**Issue by KuryKat** [dr3ams/Roguelike-Adventures-and-Dungeons-2#380]
### General Info

- [X] I didn't add any mods
- [ ] I can reproduce this issue consistently in single-player 
  - (didn't test to try and reproduce)
- [ ] I can reproduce this issue consistently in multi-player
  - (didn't test to try and reproduce)
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack
  - (didn't update the server to 1.11 yet cause didn't see there was an update)

### Your launcher

CurseForge + Prism Launcher (directory junction)

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.10a

### Describe your issue

Related to tom5454/Toms-Storage#362

----

This issue is mainly to track an issue that was caused by Tom's Simple Storage, I have [reported](https://github.com/tom5454/Toms-Storage/issues/362) the issue and I'm waiting for the dev to reply back

----

While playing RAD2 on my dedicated server, I tried to test if I could paint an Inventory Hopper, from Tom's Simple Storage, and ended up crashing the server while doing so, below it's the Crash Report and a Screenshot in-game.

Crash Report: https://mclo.gs/ErWGbyu

💥💥💥💥
![image](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/57152799/a3bd57d9-52e4-45d7-82a4-b6232dda64f6)
### Steps to reproduce the issue

1. Play the game
2. Place down Inventory Hopper
3. Try to paint it!
4. 💥💥💥

### Additional Information

[Crash Report](https://mclo.gs/ErWGbyu)

**Comment by Gunner76th** [comment]
1) please upload crash report files directly into the issue ticket.  Paste bin sites expire after a while,  and cannot be accessed by everyone.  
2) 1.10a is now outdated as 1.11 has been released.  Update your server/ client and see if this issue is still present.
