### ISSUE TITLE
[Tracking Issue] 0.6 - 0.9 World rendering errors

### ISSUE THREAD

**Issue by DoctorMage** [dr3ams/Roguelike-Adventures-and-Dungeons-2#90]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Multiple

### Modpack version

Earliest Reported Version 0.6

### Describe your issue

For an unknown reason chunks will not load in when exploring reported two times
Earliest reported modpack version 0.6
Most recent report modpack version 0.9
https://streamable.com/jemz3s
https://streamable.com/whmxxi

### Additional Information

Boop

**Comment by DoctorMage** [comment]
moved to #232
